version: '3.8'
services:
  db:
    image: mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notepad
    ports:
      - 3307:3306
    volumes: 
      - ./db/mysql-data:/var/lib/mysql